/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import static calculator.Calculator.*;
import static calculator.CalculadoraFrame.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pietro
 */
public class GUI extends javax.swing.JFrame implements ActionListener {
        private Calculator c;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        c = new Calculator();
        this.setMinimumSize(new Dimension(180, 180));
        this.setMaximumSize(new Dimension(200, 200));
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
        jButton4.setActionCommand("+");        
        jButton5.addActionListener(this);
        jButton6.addActionListener(this);
        jButton7.addActionListener(this);
        jButton8.addActionListener(this);
        jButton8.setActionCommand("-");
        jButton9.addActionListener(this);
        jButton10.addActionListener(this);
        jButton11.addActionListener(this);
        jButton12.addActionListener(this);
        jButton12.setActionCommand("*");
        jButton13.addActionListener(this);
        jButton14.addActionListener(this);
        jButton14.setActionCommand("=");
        jButton15.addActionListener(this);
        jButton15.setActionCommand("C");
        jButton16.addActionListener(this);
        jButton16.setActionCommand("/");
        jTextField1.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextField1.setText("Calculadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 2, 2));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("8");
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setText("9");
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("+");
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setText("4");
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setText("5");
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setText("6");
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(102, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("-");
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setText("1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setText("2");
        jPanel2.add(jButton10);

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setText("3");
        jPanel2.add(jButton11);

        jButton12.setBackground(new java.awt.Color(102, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("*");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setText("0");
        jPanel2.add(jButton13);

        jButton14.setBackground(new java.awt.Color(0, 0, 102));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("=");
        jPanel2.add(jButton14);

        jButton15.setBackground(new java.awt.Color(0, 102, 51));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("C");
        jPanel2.add(jButton15);

        jButton16.setBackground(new java.awt.Color(102, 0, 0));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("/");
        jPanel2.add(jButton16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
   
    EstadoCalculadora estadoCalc = EstadoCalculadora.INICIAL;
    String num1 = ""; //primeiro valor
    String num2 = ""; //segundo valor
    String sinal = "";
    String comando = "";
    String resultado="";
    String sinalglobal="";
    boolean opPronto=false;
    
    @Override
    public void actionPerformed(ActionEvent e) {
        comando = e.getActionCommand();
        System.out.printf("Comando inserido: %s\n",comando);        
        
        if(comando == "C"){
            botaoC(comando);
        }
        
        if(comando == "="){
            botaoIgual();
        }
  
        if(estadoCalc == EstadoCalculadora.INICIAL){//0 a 9 ou -
            estadoInicial(comando);
        }
        
        if(estadoCalc == EstadoCalculadora.ENTRADA1)//0 a 9
            //setarTexto(num1); //mostra o primeiro número no display
            estadoEntrada1(comando);

        if(estadoCalc == EstadoCalculadora.OPERADOR){//+ ou - ou * ou /
            estadoOperador(comando);     
        } 
        
        if(estadoCalc == EstadoCalculadora.ENTRADA2){//0 a 9
            estadoEntrada2(comando);
        }
        
        if(estadoCalc == EstadoCalculadora.CALCULANDO){
            estadoCalculando(comando);
        }
    }
    
    
    private void estadoInicial(String command){
        if(command=="+" || command=="*" || command=="/"){
            estadoCalc = EstadoCalculadora.IGNORADO;
            estadoIgnorado();
        } else if(command!="C" && command!="="){
            estadoCalc = EstadoCalculadora.ENTRADA1;
        }
    }
    
    private void estadoIgnorado(){
        num1="";
        comando="";
        estadoCalc = EstadoCalculadora.INICIAL;
    }
    
    private void estadoEntrada1(String command){
        if(num1.length()==0 && (command=="-" || command=="+")){//inserir - e + na string
            num1+=command;
            setarTexto(num1);
            estadoCalc = EstadoCalculadora.ENTRADA1;
        }
        if(num1.length()==1 && opPronto==false && (command=="-" || command=="+")){//trocar entre - e + se for preciso
            num1=command;
            setarTexto(num1);
            estadoCalc = EstadoCalculadora.ENTRADA1;
        }
        if(command!="+" && command!="-" && command !="*" && command!="/"){
            num1+=command;
            setarTexto(num1);
            opPronto=true;
            estadoCalc = EstadoCalculadora.ENTRADA1;
        }
        if(opPronto==true && (command=="+" || command=="-" || command=="*" || command=="/")){
            sinal=command;//sinal do operador
            estadoCalc = EstadoCalculadora.OPERADOR;
        }
    }
    
    private void estadoOperador(String command){
        setarTexto(num1 + " " + command);
        sinal=command;
        sinalglobal=command;
        estadoCalc = EstadoCalculadora.ENTRADA2;
    }
    
    private void estadoEntrada2(String command){
        if(num2.length()!=0 && (command=="+" || command=="-" || command=="*" || command=="/")){//trocar de sinal depois da ENTRADA1 (e antes da ENTRADA2)
            sinal=command;
            if(sinalglobal=="+")
                resultado = String.valueOf(Calculator.OperacaoSoma(num1,num2));
            if(sinalglobal=="-")
                resultado = String.valueOf(Calculator.OperacaoSubtracao(num1,num2));
            if(sinalglobal=="*")
                resultado = String.valueOf(Calculator.OperacaoMultiplicacao(num1,num2));
            if(sinalglobal=="/")
                resultado = String.valueOf(Calculator.OperacaoDivisao(num1,num2));
            num1=resultado;
            num2="";
            setarTexto(num1 + " " + sinal);
            estadoCalc = EstadoCalculadora.ENTRADA2;
        }   
        if(num2!="" && (command=="+" || command=="-" || command=="*" || command=="/")){//trocar de sinal depois da ENTRADA1 (e antes da ENTRADA2)
            sinal=command;
            setarTexto(num1 + " " + sinal);
            estadoCalc = EstadoCalculadora.OPERADOR;
        } 
        if(command!="+" && command!="-" && command!="*" && command!="/"){//executar a ENTRADA2
            num2+=command;
            setarTexto(num1 + " " + sinal + " " + num2);
        }          
    }
    
    private void estadoCalculando(String command){
        num1=resultado;
        num2="";
        estadoCalc = EstadoCalculadora.OPERADOR;
    }
 
    private void botaoC(String command){
            num1 = "";
            num2 = "";
            sinal = "";
            setarTexto("");
            opPronto=false;
            estadoCalc = EstadoCalculadora.INICIAL;    
    }
    
    private void botaoIgual(){
        if(sinal=="+")
            resultado = String.valueOf(Calculator.OperacaoSoma(num1,num2));
        if(sinal=="-")
            resultado = String.valueOf(Calculator.OperacaoSubtracao(num1,num2));
        if(sinal=="*")
            resultado = String.valueOf(Calculator.OperacaoMultiplicacao(num1,num2));
        if(sinal=="/")
            resultado = String.valueOf(Calculator.OperacaoDivisao(num1,num2));
        setarTexto(resultado);
        estadoCalc = EstadoCalculadora.CALCULANDO;        
    }
    
    private void setarTexto(String t){ //método para atualizar display
        jTextField1.setText(t);
    }    
    

}
